project:
  name: CloudFormationTest
  regions:
    - us-east-1

tests:
  my-template-test:
    template: template.yaml # Thay 'template.yaml' bằng tên file template của bạn
    parameters:
      VpcCidr: 10.0.0.0/16
      PublicSubnetCidr: 10.0.1.0/24
      PrivateSubnetCidr: 10.0.2.0/24
      NatGatewaySubnetCidr: 10.0.1.0/24
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      LatestAmiId: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
      KeyName: 'my-key-pair' # Thay bằng tên KeyPair của bạn
    regions:
      - us-east-1
